#!/bin/bash
set -e

# Configurar el servicio de systemd
if [ -x "/bin/systemctl" ]; then
    systemctl daemon-reload
    systemctl enable db-backup.service || true
    systemctl start db-backup.service || true
fi
