#!/bin/bash
set -e

# Configurar el servicio de systemd
if [ -x "/bin/systemctl" ]; then
    systemctl daemon-reload
    systemctl enable db-backup.service || true
    systemctl start db-backup.service || true
fi

# Ejecutar logrotate como el usuario dbbackupuser
sudo -u dbbackupuser logrotate /home/dbbackupuser/logrotate.conf --state /home/dbbackupuser/logrotate-state --verbose


# Agregar línea a la tabla cron del usuario dbbackupuser
sudo -u dbbackupuser bash -c "echo '05 * * * * /usr/sbin/logrotate /home/dbbackupuser/logrotate.conf --state /home/dbbackupuser/logrotate-state >> /home/dbbackupuser/cron.log 2>&1' > /tmp/dbbackupuser_cron"
sudo mv /tmp/dbbackupuser_cron /var/spool/cron/crontabs/dbbackupuser
sudo chgrp crontab /var/spool/cron/crontabs/dbbackupuser
sudo chmod 600 /var/spool/cron/crontabs/dbbackupuser

echo "Paquete db-backup instalado con éxito"
